# Use https://crates.io/crates/cargo-chef to cache dependencies.

FROM rust:1.55-buster as planner
WORKDIR /undermoon
RUN cargo install cargo-chef
COPY src /undermoon/src
COPY Cargo.toml Cargo.lock /undermoon/
RUN cargo chef prepare  --recipe-path recipe.json

FROM rust:1.55-buster as cacher
WORKDIR /undermoon
RUN cargo install cargo-chef
COPY --from=planner /undermoon/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json

FROM rust:1.55-buster as builder
WORKDIR /undermoon
COPY src /undermoon/src
COPY Cargo.toml Cargo.lock /undermoon/
# Copy over the cached dependencies
COPY --from=cacher /undermoon/target target
COPY --from=cacher $CARGO_HOME $CARGO_HOME
RUN cargo build --release

FROM buildpack-deps:buster-curl as undermoon
RUN set -ex; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        libssl-dev
WORKDIR /undermoon
COPY --from=builder /undermoon/target/release/server_proxy /bin
COPY --from=builder /undermoon/target/release/coordinator /bin
COPY --from=builder /undermoon/target/release/mem_broker /bin
