FROM rust:1.40-buster

WORKDIR /undermoon

COPY ./examples/target_volume/release/server_proxy /bin/
COPY ./examples/target_volume/release/coordinator /bin/
COPY ./examples/target_volume/release/mem_broker /bin/
