/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package clienttest;

import org.testng.annotations.*;
import static org.testng.Assert.*;

import redis.clients.jedis.HostAndPort;
import redis.clients.jedis.JedisCluster;

import java.util.List;
import java.util.function.BiFunction;

public class JedisTest {
    JedisCluster jc;

    @BeforeClass
    public void setUp() {
        var node = new HostAndPort(Utils.getNodeHost(), Utils.getNodePort());
        this.jc = new JedisCluster(node);
    }

    String genKey(String testCase, String key) {
        final var now = new java.util.Date();
        return String.format("jedis:%d:%s:%s", now.toInstant().toEpochMilli(), testCase, key);
    }

    @Test
    public void singleKeyCommand() {
        final var key = this.genKey("singleKey", "somekey");
        final var value = "value";
        this.jc.setex(key, 60, value);
        final var v = this.jc.get(key);
        assertEquals(value, v);
    }

    @Test
    public void multiKeyCommand() {
        final var key1 = this.genKey("multikey", "key1:{hashtag}");
        final var key2 = this.genKey("multikey", "key2:{hashtag}");
        final var value1 = "value1";
        final var value2 = "value2";

        this.jc.mset(key1, value1, key2, value2);
        final var values = this.jc.mget(key1, key2);
        assertEquals(values.size(), 2);
        assertEquals(values.get(0), value1);
        assertEquals(values.get(1), value2);
    }

    @Test
    public void brpoplpush() throws InterruptedException {
        final var key1 = this.genKey("blocking", "brpoplpush_key1:{hashtag}");
        final var key2 = this.genKey("blocking", "brpoplpush_key2:{hashtag}");
        final var value = "listvalue";

        Runnable blockingCmd = () -> {
            final var res = this.jc.brpoplpush(key1, key2, 60);
            assertEquals(res, value);
        };
        var thread = new Thread(blockingCmd);
        thread.start();

        Thread.sleep(1000);
        var listLen = this.jc.rpush(key1, value);
        assertEquals(listLen, Long.valueOf(1));

        thread.join();
    }

    @Test
    void blpop() throws InterruptedException {
        listBlockingCommandHelper((key1, key2) -> this.jc.blpop(60, key1, key2));
    }

    @Test
    void brpop() throws InterruptedException {
        listBlockingCommandHelper((key1, key2) -> this.jc.brpop(60, key1, key2));
    }

    void listBlockingCommandHelper(BiFunction<String, String, List<String>> cmdFunc) throws InterruptedException {
        final var key1 = this.genKey("blocking", "key1:{hashtag}");
        final var key2 = this.genKey("blocking", "key2:{hashtag}");
        final var value = "listvalue";

        Runnable blockingCmd = () -> {
            final var res = cmdFunc.apply(key1, key2);
            assertEquals(res.size(), 2);
            assertEquals(res.get(0), key2);
            assertEquals(res.get(1), value);
        };
        var thread = new Thread(blockingCmd);
        thread.start();

        Thread.sleep(1000);
        var listLen = this.jc.rpush(key2, value);
        assertEquals(listLen, Long.valueOf(1));

        thread.join();
    }

    // Jedis still does not support BZPOPMIN, BZPOPMAX
    // https://github.com/redis/jedis/issues/2177
}
