/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package clienttest;

public class App {
    public String getGreeting() {
        return "This project is only used for running unit tests!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
